<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Scenarios</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e0323cb6-eadc-486e-88cc-cd3ecfbc8a38</testSuiteGuid>
   <testCaseLink>
      <guid>8fce07b8-e7e4-4452-96d1-096f890f0ec5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SuccessfulEconomicReserve</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>728f4c78-cb4f-4aae-9d78-84ec2ad732d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82dc3105-f90b-48c7-a912-be6bee536040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12cc14ad-35de-454c-a4f4-0d75c80d0e18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89e9731b-2d1c-44d5-8aa7-935f164c5bd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8a5015f-ee3d-435b-a6e0-3718b26e62cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e22a75f-2291-440e-95a8-eff40acf33b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84b66b4c-9792-4725-8d88-b216a535e65b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FlightSchedules</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>728f4c78-cb4f-4aae-9d78-84ec2ad732d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82dc3105-f90b-48c7-a912-be6bee536040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e61b728-6d5c-4243-9445-fe1e19041a79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91c330a7-7f4f-4bac-9a6a-618256b686ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>26a14035-abc6-4187-9bf7-8a8fe3de0d76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RequieredFormat</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
