<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link</name>
   <tag></tag>
   <elementGuidId>15de07b5-68f6-497a-ae16-fc1e192ccabb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[@href='/co/es/tu-reserva/consulta-itinerarios/'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@href='/co/es/tu-reserva/consulta-itinerarios/'])[1]</value>
   </webElementProperties>
</WebElementEntity>
